dataset:
  train:
    start_date: "2010-01-04"
    end_date: "2019-06-18"
  val:
    start_date: "2019-06-19"
    end_date: "2019-12-17"
  test:
    start_date: "2019-12-18"
    end_date: "2020-06-17"

dataloader:
  batch_size: 16