dataset:
  train:
    start_date: "2011-07-04"
    end_date: "2020-12-16"
  val:
    start_date: "2020-12-17"
    end_date: "2021-06-16"
  test:
    start_date: "2021-06-17"
    end_date: "2021-12-15"

dataloader:
  batch_size: 16