dataset:
  train:
    start_date: "2011-01-04"
    end_date: "2020-06-17"
  val:
    start_date: "2020-06-18"
    end_date: "2020-12-16"
  test:
    start_date: "2020-12-17"
    end_date: "2021-06-16"

dataloader:
  batch_size: 16