dataset:
  train:
    start_date: "2012-07-04"
    end_date: "2021-12-15"
  val:
    start_date: "2021-12-16"
    end_date: "2022-06-15"
  test:
    start_date: "2022-06-16"
    end_date: "2022-12-21"

dataloader:
  batch_size: 16