dataset:
  train:
    start_date: "2014-07-04"
    end_date: "2023-12-20"
  val:
    start_date: "2023-12-21"
    end_date: "2024-06-19"
  test:
    start_date: "2024-06-20"
    end_date: "2024-12-18"

dataloader:
  batch_size: 16