from gymnasium.envs.registration import register

register(id='StockEnv-v0', entry_point='StockEnv.envs:StockMarket')
register(id='StockEnvValid-v0', entry_point='StockEnv.envs:StockMarketValid')
register(id='StockEnvLS-v0', entry_point='StockEnv.envs:StockMarketLS')
register(id='StockEnvSharp-v0', entry_point='StockEnv.envs:StockMarketSharp')
register(id='StockEnv-v1', entry_point='StockEnv.envs:StockMarketBase')
register(id='StockEnvLongOnly-v1', entry_point='StockEnv.envs:StockMarketLongOnly')
register(id='StockEnvShortOnly-v1', entry_point='StockEnv.envs:StockMarketShortOnly')
register(id='StockEnvLongDiscreteMask-v1', entry_point='StockEnv.envs:StockMarketLongDiscreteMask')
register(id='StockEnvLongDiscreteMask-v2', entry_point='StockEnv.envs:StockMarketLongDiscreteMaskV2')
register(id='StockEnvOnlyOneShare-v1', entry_point='StockEnv.envs:StockMarketOnlyOneShare')
register(id='StockEnvOnlyOneShareTest-v1', entry_point='StockEnv.envs:StockMarketOnlyOneShareTest')
register(id='StockEnvNoLimit-v1', entry_point='StockEnv.envs:StockMarketNoLimit')
register(id='StockEnvMargin-v1', entry_point='StockEnv.envs:StockMarketMargin')
register(id='StockEnvNoLimit-v2', entry_point='StockEnv.envs:StockMarketNoLimitV2')
register(id='StockEnvOnlyOneShare-v2', entry_point='StockEnv.envs:StockMarketOnlyOneShareV2')
register(id='StockEnvOnlyOneShareTest-v2', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV2')
register(id='StockEnvMargin-v2', entry_point='StockEnv.envs:StockMarketMarginV2')
register(id='StockEnvOnlyOneShare-v3', entry_point='StockEnv.envs:StockMarketOnlyOneShareV3')
register(id='StockEnvOnlyOneShareTest-v3', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV3')
register(id='StockEnvOnlyOneShare-v4', entry_point='StockEnv.envs:StockMarketOnlyOneShareV4')
register(id='StockEnvOnlyOneShareTest-v4', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV4')
register(id='StockEnvOnlyOneShare-v5', entry_point='StockEnv.envs:StockMarketOnlyOneShareV5')
register(id='StockEnvOnlyOneShareTest-v5', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV5')
register(id='StockEnvOnlyOneShare-v6', entry_point='StockEnv.envs:StockMarketOnlyOneShareV6')
register(id='StockEnvOnlyOneShareTest-v6', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV6')
register(id='StockEnvOnlyOneShare-v7', entry_point='StockEnv.envs:StockMarketOnlyOneShareV7')
register(id='StockEnvOnlyOneShareTest-v7', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV7')
register(id='StockEnvNoLimit-v3', entry_point='StockEnv.envs:StockMarketNoLimitV3')
register(id='StockEnvNoLimit-v4', entry_point='StockEnv.envs:StockMarketNoLimitV4')
# register(id='StockEnvMarginSyn', entry_point='StockEnv.envs:StockMarketMarginSyn')
# register(id='StockEnvMarginSynShort', entry_point='StockEnv.envs:StockMarketMarginSynShort')
register(id='StockEnvCombineTrader', entry_point='StockEnv.envs:StockCombineTrader')
register(id='StockEnvNoLimit2024', entry_point='StockEnv.envs:StockMarketNoLimit2024')
register(id='StockEnvOnlyOneShare-v6_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareV6_2')
register(id='StockEnvOnlyOneShare-v7_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareV7_2')
register(id='StockEnvOnlyOneShareTest-v7_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV7_2')
register(id='StockEnvOnlyOneShare-v5_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareV5_2')
register(id='StockEnvOnlyOneShareTest-v6_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV6_2')
register(id='StockEnvOnlyOneShareTest-v5_2', entry_point='StockEnv.envs:StockMarketOnlyOneShareTestV5_2')
register(id='StockEnvNoLimit-v4_2', entry_point='StockEnv.envs:StockMarketNoLimitV4_2')
register(id='StockEnvNoLimit-v3_2', entry_point='StockEnv.envs:StockMarketNoLimitV3_2')
register(id='StockEnvMarginSyn-v2', entry_point='StockEnv.envs:StockMarketMarginSynV2')
register(id='StockEnvMarginSynShort-v2', entry_point='StockEnv.envs:StockMarketMarginSynShortV2')